### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by readysloth** [klilukqq/ArchVS#2]
Что такое интринсики компилятора? (intrinsic)
Какие интринсики вы уже знаете?

**Comment by klilukqq** [comment]
Интринсики это внутренние функции, присущие компилятору, которые при вызове не будут использовать call и ret, а сразу заменятся на необходимые инструкции. Например, функции memcpy, memcmp, strlen, strcpy, strcmp и abs, их можно использовать через вызов функции, а можно использовать, как интринсики через #pragma intrinsic, в этом случае программа будет выполняться быстрее, но она может быть больше из-за дополнительного генерируемого кода.
