### ISSUE TITLE
Лабораторная 5 Вопросы

### ISSUE THREAD

**Issue by readysloth** [klilukqq/ArchVS#3]
+ Какой размер у элемента стека в FPU? 
+ Код, производящий вычисления над числами с плавающей точкой использует разные расширения на x86 и x86-64 системах. На x86 это FPU, а на x86-64?

**Comment by klilukqq** [comment]
1) Стек FPU состоит из 8 регистров, каждый из которых занимает 80 бит (мантисса занимает 64бита, порядок 15 бит, знак один бит)
2) На обоих режимах можно использовать два набора инструкций(при условии, что процессор не очень старый), это FPU и SSE, по умолчанию на x86 используется FPU, а на x86-64 SSE, но это можно изменить
