### ISSUE TITLE
Лабораторная 6 Вопросы

### ISSUE THREAD

**Issue by readysloth** [klilukqq/ArchVS#4]
+ Что такое выравнивание памяти и какой операцией оно выполняется? (это логическая операция)
+ Что такое *flexible array member* в структурах C и для чего это нужно?

**Comment by klilukqq** [comment]
1) При обычном расположение памяти между элементами существуют пустые байты, например имеется структура, содержащая 1 элемент char, 1 - long, 1 -char, именно в таком порядке, в таком случае за счет выравнивания у нас общий вес станет 8 байт, а не 6, как должно быть, оно выполняется с помощью логического сдвига
2)Гибкий массив, в который сам определяет необходимое кол-во памяти. Предположим, имеется структура, содержащая массив символов размером 30 байт. Проблема в том, что когда вы создаете переменную с использованием этой структуры, каждый раз компилятор резервирует 30 байт для массива. Если заполняется меньше 30 байтов, оставшаяся память массива будет пустой тратой, иногда может заниматься больше 30 байтов, что также вызовет проблемы при использование обычного массива.
